<html>
    <head>
        <meta charset="utf-8">
        <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>MyPlayer></title>
        <link rel="stylesheet" type="text/css" href="/pub/css/player.css">
        <script type="text/javascript" src="/pub/scripts/player.js"></script>
    </head>
<body>
    <script>
        tracks = <?=json_encode($tracks)?>;     
    </script>
    <audio id="player" preload="auto" tabindex="0" controls="" type="audio/mpeg">
        <source type="audio/mp3" src="<?=$tracks[0]['url']?>">
        Sorry, your browser does not support HTML5 audio.
    </audio>
    <ul id="playlist">
        <?for($t = 0; $t < count($tracks); ++$t):?>
            <li<?=($t == 0) ? 'class="active"': '';?>><a href="<?=$tracks[$t]['url']?>">▶ <?=$tracks[$t]['name']?></a></li> 
        <?endfor?>          
    </ul> 
    <script>initplaylist();</script> 
</body>        
